# 課題4 テキストデータ分析
## Q1

$n$-次元ベクトル空間における、任意の2つのベクトル、$ \vec{x}=(x_1,x_2,...,x_n)$、$\vec{y}=(y_1,y_2,...,y_n)$、の間のcos類似度 $cos(X,Y)$ は以下のように定義されます。

$cos(X,Y) =  \frac{\vec{x}\cdot \vec{y}}{\|x\|_2\|y\|_2}=\frac{\Sigma^{n}_{i=1}{x_{i}y_{i}}}{\sqrt{\Sigma^{n}_{i=1}x_{i}^{2}}\sqrt{\Sigma^{n}_{i=1}y_{i}^{2}}}$

入力ベクトル $\vec{x}$, $\vec{x}$ をそれぞれ`NumPy` の配列として引数で受け取り、それらのベクトル間のcos類似度を計算して返す関数 `cos_sim` を完成させてください。

In [1]:
import numpy as np

In [2]:
def cos_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

`cos_sim()`関数が完成したら、以下のセルを実行して動作を確認してください。`-1, 1, 0`がそれぞれのcos類似度です。

In [3]:
print(cos_sim(np.array([1,0]), np.array([-1,0])))
print(cos_sim(np.array([1,0]), np.array([1,0])))
print(cos_sim(np.array([1,0]), np.array([0,-1])))

-1.0
1.0
0.0


In [4]:
### このセルは変更しないでください ###
assert -1 == cos_sim(np.array([1,0]), np.array([-1,0]))
assert 1 == cos_sim(np.array([1,0]), np.array([1,0]))
assert 0 == cos_sim(np.array([1,0]), np.array([0,-1]))

## Q2
"course_list.csv"ファイルには以下のように各行に講義名のテキストデータが含まれています。以下では、このファイルを読み込み、各講義のベクトルを作成し、講義間の類似度を求めるコードを実装します。
```Python
## course_list.csvファイル
...
行動神経科学
認知心理学
性格心理学
スポーツ栄養学
グローバル教養特別演習I（１３）
認知行動障害論
スポーツバイオメカニクス
...
```
まず必要なモジュールをimportします。

In [5]:
import json
import csv
import numpy as np
import pandas as pd

### Q2.1
"course_list.csv"ファイルを1行ずつ**順番に**読み込み、その各行を要素とするリストを作成して返す`course_list`関数を完成さてください。作成されたリストは変数`courses`で受け取ります。以降の処理では、リスト`courses`のインデックスをその要素（講義名）のIDとして扱います。


In [6]:
def course_list():
    course_list = []
    with open("course_list.csv","r") as f:
        reader = csv.reader(f)
        for row in reader:
            print(row)
            course_list.append(row[0])

    return course_list

courses = course_list()

['生産システムI']
['特別講義\u3000国際紛争研究（外国語科目）']
["特別講義\u3000Japan in Today's World（外国語科目）"]
['生態統計学']
['商法演習']
['ロシア・旧ソ連法']
['技術倫理']
['健康心理学']
['機械設計及び製図']
['農作業実習']
['グローバル生命倫理']
['国法学']
['国際政治史']
['特別講義\u3000Conflict Prevention and Post-Conflict Politics（外国語科目）']
['道徳と教育']
['臨床現象学']
['教育の公共性を考える']
['専門講義']
['価値と教育Ⅲ']
['日本政治思想史']
['地域経済フィールドワーク実習']
['医薬品・医療ビジネス']
['英語科教育法III']
['教育の方法']
['高度教養特殊演習（こころの総合人間科学演習）']
['教育課程']
['教育と社会']
['高度教養特殊演習（ダイバーシティ社会をつくる技術）']
['総合日本語 I（２）（L2）']
['高度教養特殊演習（ひとをつなぐ\u3000まちをつくる）']
['総合日本語 I（１）（L1）']
['東西文明学II（言語と歴史３）']
['東西文明学II（言語と歴史１）']
['複合系計画論']
['超域文化科学高度教養（芸術作品分析法）']
['中国語学中国文学演習IX']
['スポーツ科学概論']
['プログラミング基礎']
['認知脳科学概論']
['広域システム概論I']
['学際科学概論']
['地理・空間基礎論II']
['地理・空間基礎論I']
['東西文明学III（国際社会科学２）']
['科学技術社会論']
['数理科学概論']
['進化理論[高度教養科目]']
['物質科学概論']
['広域システム概論II']
['生命科学概論']
['エネルギー科学概論']
['東西文明学I（思想と批評１）']
['情報科教育法II']
['情報科教育法I']
['英語科教育法I']
['科学技術史概論']
['理科教育法II']
['理科教育法I']
['数学科教育法I']
['公民科教育法I']
['英語科教育法II']
['東西文明学I（環境と身体５）']
['東西文明学I（環境と身体１）']
['東西文明

['共通中国語（５６）（作文）']
['日本手話（２）']
['上海語（１）（初級）']
['共通ギリシア語（５）']
['インドネシア語（３）']
['インドネシア語（２）']
['日本語（３２）アカデミックスキル（総合）（L3-L4）']
['上海語（２）（初級）']
['広東語（２）（中級）']
['共通スペイン語（７）（初級）']
['広東語（３）（初級）']
['インドネシア語（４）']
['サンスクリット語（２）']
['広東語（４）（中級）']
['共通スペイン語（５）（演習）']
['共通スペイン語（１）（会話）']
['共通韓国朝鮮語（２）']
['共通スペイン語（４）（作文）']
['共通イタリア語（１８）']
['共通スペイン語（２）（会話）']
['共通イタリア語（９）']
['共通イタリア語（１０）']
['共通イタリア語（１７）']
['共通スペイン語（６）（演習）']
['共通スペイン語（３）（作文）']
['共通イタリア語（６）']
['共通アラビア語（１０）']
['共通イタリア語（７）']
['共通イタリア語（８）']
['共通アラビア語（９）']
['共通アラビア語（６）']
['共通アラビア語（７）']
['共通アラビア語（５）']
['共通アラビア語（２）']
['共通韓国朝鮮語（１）']
['共通イタリア語（２）']
['共通アラビア語（１）']
['共通イタリア語（１）']
['共通イタリア語（３）']
['共通アラビア語（８）']
['共通アラビア語（３）']
['共通ポルトガル語（２）（初級）']
['共通ポルトガル語（４）（中級）']
['共通ポルトガル語（１）（初級）']
['共通韓国朝鮮語（２２）（初級）']
['共通スペイン語（３０）（初級）']
['インドネシア語（１）']
['共通韓国朝鮮語（１０）']
['共通韓国朝鮮語（８）']
['共通韓国朝鮮語（２６）']
['共通ポルトガル語（３）（中級）']
['共通韓国朝鮮語（７）']
['共通韓国朝鮮語（２１）（初級）']
['共通韓国朝鮮語（２５）']
['共通ギリシア語（１）']
['共通韓国朝鮮語（５）']
['ヒンディー語（１）']
['ポーランド語（１）']
['共通韓国朝鮮語（４）']
['ポーランド語（２）']
['セルビア・クロアチア語（２

['国文学演習III']
['国文学特殊講義XV']
['国文学演習VI']
['国文学特殊講義XIV']
['中国語学中国文学特殊講義III']
['中国語学中国文学特殊講義I']
['国文学演習VII']
['中国言語文化論']
['中国語学中国文学演習X']
['中国語学中国文学特殊講義II']
['国文学演習XII']
['国文学演習XI']
['印度語学印度文学演習V']
['国語学特殊講義IX']
['印度語学印度文学演習II']
['印度語学印度文学演習I']
['印度語学印度文学演習III']
['印度語学印度文学演習IV']
['中国語学中国文学特殊講義VIII']
['中国語学中国文学特殊講義VII']
['印度語学印度文学演習VI']
['中国語学中国文学特殊講義VI']
['中国語学中国文学特殊講義V']
['中国語学中国文学特殊講義IV']
['国文学演習X']
['印度語学印度文学特殊講義IV']
['中国語学概論']
['英語学英米文学特殊講義IX']
['英語学英米文学特殊講義VII']
['英語学英米文学特殊講義XII']
['英語学英米文学特殊講義X']
['英語学英米文学特殊講義V']
['英語学英米文学特殊講義IV']
['英語学英米文学特殊講義VIII']
['英語学英米文学特殊講義VI']
['英語学英米文学演習V']
['英語学英米文学演習IV']
['英語学英米文学演習III']
['英語学英米文学演習VII']
['英語学英米文学演習I']
['英語学英米文学演習VI']
['英語学英米文学特殊講義XIV']
['英語学英米文学演習II']
['英語圏言語文化演習']
['印度文学史概説II']
['英語学英米文学演習XV']
['英語学英米文学演習XIV']
['ドイツ語学概論I']
['英語学英米文学特殊講義XI']
['英語学英米文学演習XII']
['英語学英米文学演習XIII']
['フランス語学概論I']
['英語学英米文学演習XI']
['ドイツ語学ドイツ文学演習VII']
['英語学英米文学演習VIII']
['英語学英米文学演習XVI']
['ドイツ語学ドイツ文学演習VI']
['英語学英米文学演習X']
['ドイツ語学ドイツ文学演習III']
['ドイツ語学ドイツ文学特殊講義V']
['中国語学中

`course_list`関数が完成したら、以下のセルを実行して動作を確認してください。リストの長さ（講義の数）は`4628`、講義"プログラミング基礎"のID（リスト`courses`のインデックス）は`37`となります。

In [7]:
print(len(courses))
print(courses.index('プログラミング基礎'))

4628
37


In [8]:
### このセルは変更しないでください ###
assert 4628 == len(courses)
assert 37 == courses.index('プログラミング基礎')

### Q2.2
"keyword_list.csv"ファイルには以下のように各行に1単語が含まれています。
```Python
## keyword_list.csvファイル
演習
特殊
講義
科学
研究
工学
社会
コース
日本
文化
...
```
"keywor_list.csv"ファイルを1行ずつ**順番に**読み込み、その各行を要素とするリストを作成して返す`vocab_list`関数を完成さてください。作成されたリストは変数`vocab`で受け取ります。以降の処理では、リスト`vocab`のインデックスをその要素（単語）のIDとして扱います。リスト`vocab`は以降の処理における語彙となります。

In [9]:
def vocab_list():
    ### 'keyword_list.csv'ファイルを読み込み、各行をリストに追加していくコード ###
    keyword_list = []
    with open ("keyword_list.csv", "r") as f:
        reader = csv.reader(f)
        for row in reader:
            keyword_list.append(row[0])
    return keyword_list
vocab = vocab_list()

`vocab_list`関数が完成したら、以下のセルを実行して動作を確認してください。リストの長さ（単語の数）は`978`、単語"プログラミング"のID（リスト`vocab`のインデックス）は`164`となります。

In [10]:
print(len(vocab))
print(vocab.index('プログラミング'))

978
164


In [11]:
assert 978 == len(vocab)
assert 164 == vocab.index('プログラミング')

### Q2.3
リスト`courses`と`vocab`を引数で受け取り、単語のID（リスト`vocab`のその単語のインデックス）をキー、その単語のDF（Document Frequency)を値とする辞書を作成して返す`count_df`関数を作成してください。作成された辞書は変数`df`で受け取ります。この場合、ある単語のDF値はその単語を講義名に含む講義数に対応します。

In [12]:
def count_df(_courses, _vocab):
    ### 引数：
    # _courses : 講義リスト
    # _vocab: 単語リスト
    
    df = {}
    ###  単語のIDをキー、その単語のDF（Document Frequency)を値とする辞書を作成するコード ###
    ###  その単語がcourse_listの中にいくつ含まれているか ###
    for i in _vocab:
        counter = 0
        for j in _courses:
            if i in j:
                counter += 1
        df[_vocab.index(i)] = counter

    return df
df = count_df(courses, vocab)

`count_df`関数が完成したら、以下のセルを実行して動作を確認してください。辞書の長さは`978`、単語"プログラミング"（IDは`164`）のDFは`23`となります。

In [13]:
print(len(df))
print(164, vocab[164], df[164])

978
164 プログラミング 23


In [14]:
assert 978 == len(df)
assert 23 == df[164]

### Q2.4.1
リスト`vocab`の各単語を次元とする講義ベクトルを考えます。講義ベクトルの長さはリスト`vocab`の長さと等しく、リスト`vocab`のインデックス`i`の単語`vocab[i]`が講義名に含まれる時、講義ベクトルの`i`番目の要素は`1`、含まれなければ`0`とします。

以下では、リスト`courses`と`vocab`を引数で受け取り、リスト`courses`の各講義のベクトルを行、リスト`vocab`の各単語を列とした`NumPy`の行列を作成して返す`lec_word_matrix`関数を完成させてください。作成した講義-単語行列は、講義（行）の講義名に単語（列）が含まれていれば、その要素が1であるような行列です。

In [15]:
def lec_word_matrix(_courses, _vocab):
    ### 引数：
    # _courses : 講義リスト
    # _vocab: 単語リスト
    ### (講義数, 単語数)の行列を初期化するコード （ヒント np.zeros()) ###
    mat = np.zeros((len(_courses), len(_vocab)))
    ### 講義名courses[i]が単語vocab[j]を含んでいれば lec_word[i,j]=1とする処理のコード ###
    for i in _courses:
        for j in _vocab:
            if j in i:
                mat[_courses.index(i), _vocab.index(j)] = 1
    return mat

`lec_word_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した講義-単語行列の要素の値の和は`17731`となります。

In [16]:
np.sum(lec_word_matrix(courses, vocab))

17731.0

In [17]:
assert 17731 == np.sum(lec_word_matrix(courses, vocab))

### Q2.4.2
Q2.4.1で作成した講義-単語行列の各要素を、その講義の講義名に単語が含まれるか否かの1or0ではなく、その講義の講義名に単語が何回含まれるか（TF: Term Frequency)で表した行列を作成して返す`lec_word_tf_matrix`関数を完成させてください。

In [18]:
def lec_word_tf_matrix(_courses, _vocab):
    ### 引数：
    # _courses : 講義リスト
    # _vocab: 単語リスト
    
    ### (講義数, 単語数)の行列を初期化するコード （ヒント np.zeros()) ###
    mat = np.zeros((len(_courses), len(_vocab)))
    ###  lec_word[i,j]="講義名courses[i]に単語vocab[j]が含まれる数"、とする処理のコード ###
    for i in _courses:
        for j in _vocab:
            if j in i:
                tmp_list = i.split(j)
                mat[_courses.index(i), _vocab.index(j)] = len(tmp_list)-1

    return mat

`lec_word_tf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した講義-単語行列の要素の値の和は`18045`となります。

In [19]:
np.sum(lec_word_tf_matrix(courses, vocab))

18045.0

In [20]:
assert 18045 == np.sum(lec_word_tf_matrix(courses, vocab))

講義「情報社会及び情報倫理」には「情報」が2回含まれるので対応する行列の要素の値は2となります。

In [21]:
lec_word_tf_matrix(courses, vocab)[courses.index('情報社会及び情報倫理'), vocab.index('情報')]

2.0

### Q2.4.3
Q2.4.2で作成した講義-単語行列の各要素（講義`i`の単語`j`の$TF_{ij}$）にその単語のIDF値を掛けたTFIDF値を要素とする行列を作成して返す`lec_word_tfidf_matrix`関数を完成させてください。作成した行列は変数`tfidf_matrix`で受け取ります。

ここで、講義`i`、単語`j`のTFIDF値は以下のように定義されます。
```Python
TFIDF=TF_ij*log(すべての講義数/単語jのDF)=TF_ij*log(len(courses)/df[j])
```
`log`の計算には`np.log()`を使用してよいです。

In [22]:
def lec_word_tfidf_matrix(_courses, _vocab, _df):
    ### 引数：
    # _courses : 講義リスト
    # _vocab: 単語リスト
    # _df: DF辞書
    
    ### (講義数, 単語数)の行列を初期化するコード （ヒント np.zeros()) ###
    mat = np.zeros((len(_courses), len(_vocab)))
    ###  lec_word[i,j]="講義名courses[i]の単語vocab[j]のTFIDF値"、とする処理のコード ###
    for i in _courses:
        for j in _vocab:
            if j in i:
                tmp_list = i.split(j)
                mat[_courses.index(i), _vocab.index(j)] = (len(tmp_list)-1) * (np.log(len(courses) / _df[_vocab.index(j)]))

    return mat

tfidf_matrix = lec_word_tfidf_matrix(courses, vocab, df)

`lec_word_tfidf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した講義-単語行列の要素の値の和の整数部分は`78877`となります。

In [23]:
np.sum(tfidf_matrix)

78877.29015665206

In [24]:
assert 78877==int(np.sum(tfidf_matrix))

講義「情報社会及び情報倫理」には「情報」が2回含まれ、「情報」のDF値は155なので対応する行列の要素の値は$2*log(4628/155)\simeq6.79$となります。

In [25]:
tfidf_matrix[courses.index('情報社会及び情報倫理'), vocab.index('情報')]

6.792909942788641

### Q2.5
Q2.4.3で作成した講義-単語行列を元に、入力の講義に対してcos類似度に基づいて他のすべての講義との類似度を計算し、類似する講義名をキー、その類似度を値とした辞書を返す以下の`find_similar_course`関数を完成させてください。その際、入力の講義および類似度が0の講義は辞書に含めないようにしてください。cos類似度の計算にはQ1で作成した関数を使ってもよいです。

In [26]:
def find_similar_course(_target, _matrix, _courses):
    ### 引数：
    # _target:  入力講義のID
    # _matrix: 講義-単語行列（TFIDF値)
    # _courses: 講義リスト

    ### 入力講義のベクトル_matrix[target]と各講義iのベクトル_matrix[i]の類似度を計算するコード ###
    target_mat = _matrix[_target]
    sim_dic = {}
    for i in range(len(_courses)):
        sim = cos_sim(target_mat, _matrix[i])
        if not sim == 1:
            if not sim == 0:
                sim_dic[_courses[i]] = sim
    return sim_dic

`find_similar_course`関数が完成したら、以下のセルを実行して動作を確認してください。入力の講義に類似した上位の講義は、`医学データの統計解析、応用データ解析、システムデータ解析、統計解析、地球物理データ解析`となります。

In [27]:
title="医学データの統計解析実習" # 入力の講義名

results=find_similar_course(courses.index(title), tfidf_matrix, courses) # 類似講義の辞書を受け取る

df=pd.DataFrame(list(results.items()), columns=['title', "similarity"]) # 類似度が上位の講義を表示
df.sort_values(by='similarity', ascending=False).head(10)

title  similarity
226  医学データの統計解析    0.951426
118     応用データ解析    0.591201
175   システムデータ解析    0.551596
10         統計解析    0.549322
8     地球物理データ解析    0.518601
184    特別講義　法医学    0.459255
221     経済データ分析    0.394401
273      心理統計実習    0.392754
203         統計Ⅰ    0.385049
171         統計Ⅱ    0.385049

In [28]:
assert 305 == len(find_similar_course(courses.index("医学データの統計解析実習"), tfidf_matrix, courses))